#!/usr/bin/env bash
# themes/apply-theme.sh — generates tool-specific color files from a theme palette
# Usage: bash themes/apply-theme.sh [theme-name]   (default: flexoki)
#        make theme THEME=opencode

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES="$(cd "$SCRIPT_DIR/.." && pwd)"

THEME="${1:-flexoki}"
THEME_FILE="$SCRIPT_DIR/${THEME}.sh"

if [[ ! -f "$THEME_FILE" ]]; then
    echo "Error: theme file '$THEME_FILE' not found."
    echo "Available themes: $(ls "$SCRIPT_DIR"/*.sh | xargs -n1 basename | sed 's/\.sh//' | grep -v apply-theme | tr '\n' ' ')"
    exit 1
fi

source "$THEME_FILE"
mkdir -p "$SCRIPT_DIR/generated"

echo "Applying theme: $THEME"

# ---------------------------------------------------------------------------
# 1. themes/generated/kitty-colors.conf
# ---------------------------------------------------------------------------
cat > "$SCRIPT_DIR/generated/kitty-colors.conf" << EOF
# Generated by themes/apply-theme.sh (theme: ${THEME}) — edit themes/${THEME}.sh instead

foreground #${KITTY_COLOR7}
background #${KITTY_COLOR0}

cursor            #${KITTY_CURSOR}
cursor_text_color #${KITTY_CURSOR_TEXT}

selection_foreground #${KITTY_SELECTION_FG}
selection_background #${KITTY_SELECTION_BG}

url_color #${KITTY_URL}

# Normal colors (0-7)
color0  #${KITTY_COLOR0}
color1  #${KITTY_COLOR1}
color2  #${KITTY_COLOR2}
color3  #${KITTY_COLOR3}
color4  #${KITTY_COLOR4}
color5  #${KITTY_COLOR5}
color6  #${KITTY_COLOR6}
color7  #${KITTY_COLOR7}

# Bright colors (8-15)
color8  #${KITTY_COLOR8}
color9  #${KITTY_COLOR9}
color10 #${KITTY_COLOR10}
color11 #${KITTY_COLOR11}
color12 #${KITTY_COLOR12}
color13 #${KITTY_COLOR13}
color14 #${KITTY_COLOR14}
color15 #${KITTY_COLOR15}

active_tab_foreground   #${KITTY_ACTIVE_TAB_FG}
active_tab_background   #${KITTY_ACTIVE_TAB_BG}
inactive_tab_foreground #${KITTY_INACTIVE_TAB_FG}
inactive_tab_background #${KITTY_INACTIVE_TAB_BG}
EOF

echo "  wrote themes/generated/kitty-colors.conf"

# ---------------------------------------------------------------------------
# 2. themes/generated/tmux-colors.conf
# ---------------------------------------------------------------------------
cat > "$SCRIPT_DIR/generated/tmux-colors.conf" << EOF
# Generated by themes/apply-theme.sh (theme: ${THEME}) — edit themes/${THEME}.sh instead

set -g @thm_bg        "#${THM_BG}"
set -g @thm_fg        "#${THM_FG}"
set -g @thm_red       "#${THM_TMUX_RED}"
set -g @thm_green     "#${THM_TMUX_GREEN}"
set -g @thm_yellow    "#${THM_TMUX_YELLOW}"
set -g @thm_blue      "#${THM_BLUE}"
set -g @thm_pink      "#${THM_BLUE6}"
set -g @thm_mauve     "#${THM_BLUE5}"
set -g @thm_peach     "#${THM_ORANGE}"
set -g @thm_maroon    "#${THM_TMUX_MAROON}"
set -g @thm_rosewater "#${THM_TMUX_ROSEWATER}"
set -g @thm_overlay_0 "#${THM_OVERLAY_0}"
set -g @thm_surface_0 "#${THM_SURFACE_0}"

set -g @thm_music       "#${THM_MUSIC}"
set -g @thm_separator   "#${THM_SEPARATOR}"
set -g @thm_weather     "#${THM_WEATHER}"
set -g @thm_bluetooth   "#${THM_BLUETOOTH}"
set -g @thm_vpn         "#${THM_VPN}"
set -g @thm_time        "#${THM_TIME}"
set -g @thm_battery_ok  "#${THM_BATTERY_OK}"
set -g @thm_battery_low "#${THM_BATTERY_LOW}"
EOF

echo "  wrote themes/generated/tmux-colors.conf"

# ---------------------------------------------------------------------------
# 3. nvim/lua/palette.lua
# ---------------------------------------------------------------------------
cat > "$DOTFILES/nvim/lua/palette.lua" << EOF
-- Generated by themes/apply-theme.sh (theme: ${THEME}) — edit themes/${THEME}.sh instead
local M = {}

M.bg            = "#${NVIM_BG}"
M.bg_dark       = "#${THM_BG_DARK}"
M.bg_highlight  = "#${THM_BG_HIGHLIGHT}"
M.bg_popup      = "#${THM_BG_POPUP}"
M.bg_search     = "#${THM_BG_SEARCH}"
M.bg_sidebar    = "#${THM_BG_DARK}"
M.bg_statusline = "#${THM_BG_DARK}"
M.bg_visual     = "#${THM_BG_VISUAL}"
M.surface_0     = "#${THM_SURFACE_0}"
M.overlay_0     = "#${THM_OVERLAY_0}"

M.fg            = "#${THM_FG}"
M.fg_dark       = "#${THM_FG_DARK}"
M.fg_gutter     = "#${THM_FG_GUTTER}"
M.dark3         = "#${THM_DARK3}"
M.dark5         = "#${THM_DARK5}"

M.blue          = "#${THM_BLUE}"
M.blue1         = "#${THM_BLUE1}"
M.blue2         = "#${THM_BLUE2}"
M.blue5         = "#${THM_BLUE5}"
M.blue6         = "#${THM_BLUE6}"
M.blue7         = "#${THM_BLUE7}"
M.cyan          = "#${THM_CYAN}"
M.teal          = "#${THM_CYAN}"
M.green         = "#${THM_GREEN}"
M.green1        = "#${THM_GREEN}"
M.green2        = "#${THM_GREEN}"
M.red           = "#${THM_RED}"
M.red1          = "#${THM_RED1}"
M.orange        = "#${THM_ORANGE}"
M.yellow        = "#${THM_YELLOW}"
M.magenta       = "#${THM_MAGENTA}"
M.magenta2      = "#${THM_MAGENTA}"
M.purple        = "#${THM_PURPLE}"
M.pink          = "#${THM_PURPLE}"
M.comment       = "#${THM_COMMENT}"

M.mode_normal     = "#${NVIM_MODE_NORMAL}"
M.mode_insert     = "#${NVIM_MODE_INSERT}"
M.mode_visual     = "#${NVIM_MODE_VISUAL}"
M.mode_replace    = "#${NVIM_MODE_REPLACE}"
M.mode_command    = "#${NVIM_MODE_COMMAND}"
M.mode_command_fg = "#${NVIM_MODE_COMMAND_FG}"

return M
EOF

echo "  wrote nvim/lua/palette.lua"
echo "Done. Reload: kitty (ctrl+shift+F5), tmux (tmux source ~/.tmux.conf), nvim (restart)."
